#!/bin/sh
# Regenerates cli/ca_bundle.h from Mozilla's root store, as published by the
# curl project. A released binary is statically linked and cannot rely on the
# host having /etc/ssl/certs, so the roots travel with it.
#
#   sh tools/make_ca_bundle.sh
#
# Certificates are emitted one raw string literal each rather than as a single
# blob: MSVC caps a string literal at 65535 characters, and the whole bundle is
# far past that.
set -e

url=https://curl.se/ca/cacert.pem
out="$(dirname "$0")/../cli/ca_bundle.h"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

curl -sSfL "$url" -o "$tmp"
stamp=$(grep -m1 'Certificate data from Mozilla as of:' "$tmp" |
        sed 's/.*as of: //')
count=$(grep -c 'BEGIN CERTIFICATE' "$tmp")

{
  echo "// Generated by tools/make_ca_bundle.sh -- do not edit."
  echo "//"
  echo "// Mozilla's root CA store, $count certificates, as published by the curl"
  echo "// project at $url"
  echo "// Certificate data from Mozilla as of: $stamp"
  echo "#pragma once"
  echo
  echo "namespace coolth_cli {"
  echo
  echo "// Each entry is one PEM certificate, NUL terminated, ready for"
  echo "// mbedtls_x509_crt_parse."
  echo "inline const char *const kCaCertificates[] = {"
  awk '
    /-----BEGIN CERTIFICATE-----/ { inside = 1; printf "    R\"PEM("
    }
    inside { print }
    /-----END CERTIFICATE-----/ { if (inside) { print ")PEM\"," ; inside = 0 } }
  ' "$tmp"
  echo "};"
  echo
  echo "}  // namespace coolth_cli"
} > "$out"

echo "wrote $out ($count certificates, $(wc -c < "$out") bytes)"
